/* TrixTech s.r.o. @2025 */

window.TranslateWidget = {
  name: 'TranslateWidget',
  type: 'response',
  match: ({ trace }) =>
    trace.type === 'ext_translateWidget' ||
    trace.payload?.name === 'ext_translateWidget',

  render: ({ trace, element }) => {
    let incomingLang = trace.payload?.lang || 'cs';
    if (typeof incomingLang === 'object' && incomingLang !== null) {
      incomingLang = incomingLang.lang || incomingLang.language || 'cs';
    }
    incomingLang = String(incomingLang).toLowerCase().trim();
    
    const lang = (incomingLang.includes('en') || incomingLang.includes('english')) ? 'en' : 'cs';
    const label = lang === 'cs'
      ? 'Zvolený jazyk je: 🇨🇿 Čeština'
      : 'Language in use: 🇺🇸 English';

    const container = document.createElement('div');
    container.className = 'vfrc-message vfrc-message--extension TranslateWidget';

    const style = document.createElement('style');
    style.textContent = `
      .vfrc-message.vfrc-message--extension.TranslateWidget {
        opacity: 1;
        transition: opacity 0.3s ease-out;
        width: 100%;
        display: block;
      }
      .vfrc-message.vfrc-message--extension.TranslateWidget.hide {
        opacity: 0;
        visibility: hidden;
        pointer-events: none;
      }
      .translate-box {
        display: flex;
        align-items: center;
        gap: 8px;
        padding: 8px 12px;
        margin-bottom: 8px;
        width: 100%;
        box-sizing: border-box;
        background-color: #F9FAFB;
        border-radius: 12px;
        border: 1px solid #E5E7EB;
      }
      .translate-text {
        flex: 1;
        min-width: 0;
        color: rgba(26, 30, 35, 0.7);
        font-size: 12px;
        line-height: 1.3;
        font-family: var(--_1bof89na);
        font-style: italic;
        display: flex;
        flex-direction: column;
        opacity: 1;
        transform: translateY(0);
        transition: opacity 0.3s ease-out, transform 0.3s ease-out;
      }
      button.vfrc-button[label="Start new chat"]::before {
        content: "${lang === 'cs' ? 'Spustit nový chat' : 'Start new chat'}" !important;
      }
      button.vfrc-button[label="Cancel"]::before {
        content: "${lang === 'cs' ? 'Zrušit' : 'Cancel'}" !important;
      }
      #vfrc-start-chat::before {
        content: "${lang === 'cs' ? 'Spustit nový chat' : 'Start new chat'}" !important;
      }
      .dio4eo4::before {
        content: "${lang === 'cs' ? 'Poznejte město Litovel' : 'Discover the city of Litovel'}" !important;
        font-size: 16px !important;
        color: #656d75 !important;
      }
      .dio4eo5::before {
        content: "${lang === 'cs' ? 'prostřednictvím našeho AI asistenta' : 'through our AI assistant'}" !important;
        font-size: 14px !important;
        color: #656d75 !important;
      }
      .ticwq62::before {
        content: "${lang === 'cs' ? 'Chat byl ukončen' : 'Chat has ended'}" !important;
      }
      ._11kfxpg7::before {
        content: "${lang === 'cs' ? 'Odpověď byla generována pomocí AI' : 'The response was generated by AI'}" !important;
      }
    `;

    const text = document.createElement('span');
    text.className = 'translate-text';
    text.textContent = label;

    const box = document.createElement('div');
    box.className = 'translate-box';
    box.appendChild(text);

    container.appendChild(style);
    container.appendChild(box);

    const deepQuerySelector = (root, selector) => {
      const found = root.querySelector(selector);
      if (found) return found;
      for (const el of root.querySelectorAll('*')) {
        if (el.shadowRoot) {
          const nested = deepQuerySelector(el.shadowRoot, selector);
          if (nested) return nested;
        }
      }
      return null;
    };

    const deepQS = (root, sel) => {
      const stack = [root];
      while (stack.length) {
        const n = stack.pop();
        if (n.querySelector) {
          const f = n.querySelector(sel);
          if (f) return f;
        }
        if (n.shadowRoot) stack.push(n.shadowRoot);
        n.childNodes && n.childNodes.forEach(c => { if (c.nodeType === 1) stack.push(c); });
      }
      return null;
    };

    const updateTexts = () => {
      const placeholder = lang === 'cs' ? 'Napište váš dotaz...' : 'Enter your query...';
      const textarea = deepQuerySelector(document, 'textarea.vfrc-chat-input');
      if (textarea) textarea.placeholder = placeholder;
    };

    const patchUIElements = () => {
      const launcherBtn = deepQS(document, 'button.vfrc-launcher');
      if (launcherBtn) {
        if (lang === 'cs') {
          launcherBtn.title = launcherBtn.title.includes('Close') || launcherBtn.title.includes('Zavřít') ? 'Zavřít chat' : 'Otevřít chat';
        } else {
          launcherBtn.title = launcherBtn.title.includes('Close') || launcherBtn.title.includes('Zavřít') ? 'Close chat' : 'Open chat';
        }
        launcherBtn.setAttribute('aria-label', launcherBtn.title);
      }

      const sendBtn = deepQS(document, 'button[title="Send"], button[aria-label="Send"], button[title="Odeslat"], button[aria-label="Odeslat"]');
      if (sendBtn) {
        if (lang === 'cs') {
          sendBtn.title = 'Odeslat';
          sendBtn.setAttribute('aria-label', 'Odeslat');
        } else {
          sendBtn.title = 'Send';
          sendBtn.setAttribute('aria-label', 'Send');
        }
      }

      const allSendBtns = document.querySelectorAll('button[title="Send"], button[aria-label="Send"], button[title="Odeslat"], button[aria-label="Odeslat"]');
      allSendBtns.forEach(btn => {
        if (lang === 'cs') {
          btn.title = 'Odeslat';
          btn.setAttribute('aria-label', 'Odeslat');
        } else {
          btn.title = 'Send';
          btn.setAttribute('aria-label', 'Send');
        }
      });

      const allLauncherBtns = document.querySelectorAll('button[title*="Open chat agent"], button[title*="Close chat agent"], button[title*="Otevřít chat"], button[title*="Zavřít chat"]');
      allLauncherBtns.forEach(btn => {
        if (lang === 'cs') {
          btn.title = btn.title.includes('Close') || btn.title.includes('Zavřít') ? 'Zavřít chat' : 'Otevřít chat';
        } else {
          btn.title = btn.title.includes('Close') || btn.title.includes('Zavřít') ? 'Close chat' : 'Open chat';
        }
        btn.setAttribute('aria-label', btn.title);
      });

      const allElements = document.querySelectorAll('*');
      allElements.forEach(el => {
        if (lang === 'cs') {
          if (el.textContent === 'Send') el.textContent = 'Odeslat';
          if (el.textContent === 'Open chat agent') el.textContent = 'Otevřít chat';
          if (el.textContent === 'Close chat agent') el.textContent = 'Zavřít chat';
        } else {
          if (el.textContent === 'Odeslat') el.textContent = 'Send';
          if (el.textContent === 'Otevřít chat') el.textContent = 'Open chat';
          if (el.textContent === 'Zavřít chat') el.textContent = 'Close chat';
        }
      });
    };

    const updateAllTexts = () => {
      updateTexts();
      patchUIElements();
    };

    updateAllTexts();

    const patchInterval = setInterval(patchUIElements, 100);

    const observer = new MutationObserver(() => {
      updateAllTexts();
    });
    observer.observe(document, { subtree: true, childList: true, characterData: true });

    const cleanupObserver = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        mutation.removedNodes.forEach((node) => {
          if (node === container || (node.nodeType === 1 && node.contains && node.contains(container))) {
            clearInterval(patchInterval);
            observer.disconnect();
            cleanupObserver.disconnect();
          }
        });
      });
    });
    cleanupObserver.observe(element.parentElement || document.body, {
      childList: true,
      subtree: true
    });

    element.innerHTML = '';
    element.appendChild(container);
  }
};